In [8]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import display

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", None)
plt.rcParams.update({'figure.figsize': (12, 6),'figure.dpi':120})

In [3]:
products = pd.read_csv("../data/raw/products.csv")
orders = pd.read_csv("../data/raw/orders.csv")
order_items = pd.read_csv("../data/raw/order_items.csv")
order_item_refunds = pd.read_csv("../data/raw/order_item_refunds.csv")
website_pageviews = pd.read_csv("../data/raw/website_pageviews.csv")
website_sessions = pd.read_csv("../data/raw/website_sessions.csv")

In [4]:
datasets = {
    "products"          : products,
    "orders"            : orders,
    "order_items"       : order_items,
    "order_item_refunds": order_item_refunds,
    "website_pageviews" : website_pageviews,
    "website_sessions"  : website_sessions
}

In [12]:
for name,df in datasets.items():
    print("-" * 60)
    print(f"{name}".upper())
    print("-" * 60)
    
    display(df.head())
    
    print(f'Shape : {df.shape}')
    
    print("\nData Types:")
    display(df.dtypes.to_frame(name = "Data Type"))
    
    print("\nDuplicate:")
    display(df.duplicated().sum())
    
    print("\nMissing Values:")
    display(df.isnull().sum().to_frame(name = "Missing Count"))
    
    print("\nMemory Usage (MB):")
    memory_mb = (
        df.memory_usage(deep=True).sum()
        / 1024**2
    )

    print(f"{memory_mb:.2f} MB")

    print("\n")

------------------------------------------------------------
PRODUCTS
------------------------------------------------------------

   product_id           created_at                product_name
0           1  2012-03-19 08:00:00      The Original Mr. Fuzzy
1           2  2013-01-06 13:00:00       The Forever Love Bear
2           3  2013-12-12 09:00:00    The Birthday Sugar Panda
3           4  2014-02-05 10:00:00  The Hudson River Mini bear

Shape : (4, 3)

Data Types:

             Data Type
product_id       int64
created_at      object
product_name    object

Duplicate:

np.int64(0)

Missing Values:

              Missing Count
product_id                0
created_at                0
product_name              0

Memory Usage (MB):
0.00 MB


------------------------------------------------------------
ORDERS
------------------------------------------------------------

   order_id           created_at  website_session_id  user_id  primary_product_id  items_purchased  price_usd  cogs_usd
0         1  2012-03-19 10:42:46                  20       20                   1                1      49.99     19.49
1         2  2012-03-19 19:27:37                 104      104                   1                1      49.99     19.49
2         3  2012-03-20 06:44:45                 147      147                   1                1      49.99     19.49
3         4  2012-03-20 09:41:45                 160      160                   1                1      49.99     19.49
4         5  2012-03-20 11:28:15                 177      177                   1                1      49.99     19.49

Shape : (32313, 8)

Data Types:

                   Data Type
order_id               int64
created_at            object
website_session_id     int64
user_id                int64
primary_product_id     int64
items_purchased        int64
price_usd            float64
cogs_usd             float64

Duplicate:

np.int64(0)

Missing Values:

                    Missing Count
order_id                        0
created_at                      0
website_session_id              0
user_id                         0
primary_product_id              0
items_purchased                 0
price_usd                       0
cogs_usd                        0

Memory Usage (MB):
3.82 MB


------------------------------------------------------------
ORDER_ITEMS
------------------------------------------------------------

   order_item_id           created_at  order_id  product_id  is_primary_item  price_usd  cogs_usd
0              1  2012-03-19 10:42:46         1           1                1      49.99     19.49
1              2  2012-03-19 19:27:37         2           1                1      49.99     19.49
2              3  2012-03-20 06:44:45         3           1                1      49.99     19.49
3              4  2012-03-20 09:41:45         4           1                1      49.99     19.49
4              5  2012-03-20 11:28:15         5           1                1      49.99     19.49

Shape : (40025, 7)

Data Types:

                Data Type
order_item_id       int64
created_at         object
order_id            int64
product_id          int64
is_primary_item     int64
price_usd         float64
cogs_usd          float64

Duplicate:

np.int64(0)

Missing Values:

                 Missing Count
order_item_id                0
created_at                   0
order_id                     0
product_id                   0
is_primary_item              0
price_usd                    0
cogs_usd                     0

Memory Usage (MB):
4.43 MB


------------------------------------------------------------
ORDER_ITEM_REFUNDS
------------------------------------------------------------

   order_item_refund_id           created_at  order_item_id  order_id  refund_amount_usd
0                     1  2012-04-06 11:32:43             57        57              49.99
1                     2  2012-04-13 01:09:43             74        74              49.99
2                     3  2012-04-15 07:03:48             71        71              49.99
3                     4  2012-04-17 20:00:37            118       118              49.99
4                     5  2012-04-22 20:53:49            116       116              49.99

Shape : (1731, 5)

Data Types:

                     Data Type
order_item_refund_id     int64
created_at              object
order_item_id            int64
order_id                 int64
refund_amount_usd      float64

Duplicate:

np.int64(0)

Missing Values:

                      Missing Count
order_item_refund_id              0
created_at                        0
order_item_id                     0
order_id                          0
refund_amount_usd                 0

Memory Usage (MB):
0.17 MB


------------------------------------------------------------
WEBSITE_PAGEVIEWS
------------------------------------------------------------

   website_pageview_id           created_at  website_session_id pageview_url
0                    1  2012-03-19 08:04:16                   1        /home
1                    2  2012-03-19 08:16:49                   2        /home
2                    3  2012-03-19 08:26:55                   3        /home
3                    4  2012-03-19 08:37:33                   4        /home
4                    5  2012-03-19 09:00:55                   5        /home

Shape : (1188124, 4)

Data Types:

                    Data Type
website_pageview_id     int64
created_at             object
website_session_id      int64
pageview_url           object

Duplicate:

np.int64(0)

Missing Values:

                     Missing Count
website_pageview_id              0
created_at                       0
website_session_id               0
pageview_url                     0

Memory Usage (MB):
163.22 MB


------------------------------------------------------------
WEBSITE_SESSIONS
------------------------------------------------------------

   website_session_id           created_at  user_id  is_repeat_session utm_source utm_campaign utm_content device_type             http_referer
0                   1  2012-03-19 08:04:16        1                  0    gsearch     nonbrand      g_ad_1      mobile  https://www.gsearch.com
1                   2  2012-03-19 08:16:49        2                  0    gsearch     nonbrand      g_ad_1     desktop  https://www.gsearch.com
2                   3  2012-03-19 08:26:55        3                  0    gsearch     nonbrand      g_ad_1     desktop  https://www.gsearch.com
3                   4  2012-03-19 08:37:33        4                  0    gsearch     nonbrand      g_ad_1     desktop  https://www.gsearch.com
4                   5  2012-03-19 09:00:55        5                  0    gsearch     nonbrand      g_ad_1      mobile  https://www.gsearch.com

Shape : (472871, 9)

Data Types:

                   Data Type
website_session_id     int64
created_at            object
user_id                int64
is_repeat_session      int64
utm_source            object
utm_campaign          object
utm_content           object
device_type           object
http_referer          object

Duplicate:

np.int64(0)

Missing Values:

                    Missing Count
website_session_id              0
created_at                      0
user_id                         0
is_repeat_session               0
utm_source                  83328
utm_campaign                83328
utm_content                 83328
device_type                     0
http_referer                39917

Memory Usage (MB):
167.61 MB

#### Transform the create_at column to weekday, day, and month format.
#### Address missing values within the WEBSITE_SESSIONS dataset.

In [17]:
for name, df in datasets.items():
    print("-" * 60)
    print(f"Dataset :{name.upper()}" )
    print("-" * 60)
    
    print("\nDescriptive:")
    display(df.describe().T.round(2))

------------------------------------------------------------
Dataset :PRODUCTS
------------------------------------------------------------

Descriptive:

            count  mean   std  min   25%  50%   75%  max
product_id    4.0   2.5  1.29  1.0  1.75  2.5  3.25  4.0

------------------------------------------------------------
Dataset :ORDERS
------------------------------------------------------------

Descriptive:

                      count       mean        std    min        25%        50%        75%        max
order_id            32313.0   16157.00    9328.10   1.00    8079.00   16157.00   24235.00   32313.00
website_session_id  32313.0  258292.29  132427.65  20.00  144828.00  263554.00  374799.00  472818.00
user_id             32313.0  215691.62  108402.20  13.00  124135.00  221461.00  310542.00  394273.00
primary_product_id  32313.0       1.39       0.73   1.00       1.00       1.00       2.00       4.00
items_purchased     32313.0       1.24       0.43   1.00       1.00       1.00       1.00       2.00
price_usd           32313.0      59.99      17.81  29.99      49.99      49.99      59.99     109.98
cogs_usd            32313.0      22.36       6.24   9.49      19.49      19.49      22.49      41.98

------------------------------------------------------------
Dataset :ORDER_ITEMS
------------------------------------------------------------

Descriptive:

                   count      mean       std    min       25%       50%       75%       max
order_item_id    40025.0  20013.00  11554.37   1.00  10007.00  20013.00  30019.00  40025.00
order_id         40025.0  17121.96   9053.77   1.00   9871.00  17490.00  24818.00  32313.00
product_id       40025.0      1.77      1.09   1.00      1.00      1.00      2.00      4.00
is_primary_item  40025.0      0.81      0.39   0.00      1.00      1.00      1.00      1.00
price_usd        40025.0     48.43      8.01  29.99     49.99     49.99     49.99     59.99
cogs_usd         40025.0     18.05      3.86   9.49     19.49     19.49     19.49     22.49

------------------------------------------------------------
Dataset :ORDER_ITEM_REFUNDS
------------------------------------------------------------

Descriptive:

                       count      mean       std    min      25%       50%       75%       max
order_item_refund_id  1731.0    866.00    499.84   1.00   433.50    866.00   1298.50   1731.00
order_item_id         1731.0  18472.21  11438.07  57.00  7417.00  19858.00  26900.00  39950.00
order_id              1731.0  15868.24   9096.06  57.00  7412.00  17375.00  22539.50  32255.00
refund_amount_usd     1731.0     49.30      4.96  29.99    49.99     49.99     49.99     59.99

------------------------------------------------------------
Dataset :WEBSITE_PAGEVIEWS
------------------------------------------------------------

Descriptive:

                         count       mean        std  min        25%       50%        75%        max
website_pageview_id  1188124.0  594062.50  342982.00  1.0  297031.75  594062.5  891093.25  1188124.0
website_session_id   1188124.0  244458.52  135619.86  1.0  127786.00  247808.0  362739.00   472871.0

------------------------------------------------------------
Dataset :WEBSITE_SESSIONS
------------------------------------------------------------

Descriptive:

                       count       mean        std  min       25%       50%       75%       max
website_session_id  472871.0  236436.00  136506.24  1.0  118218.5  236436.0  354653.5  472871.0
user_id             472871.0  198037.97  111993.00  1.0  101966.5  199483.0  294433.0  394318.0
is_repeat_session   472871.0       0.17       0.37  0.0       0.0       0.0       0.0       1.0